### PR TITLE
Lms 199 google calendar sending notification to the concerned batch/ program on creation of new event

### PR DESCRIPTION
**Pull request by Shemeeba**

### CODE REVIEW

**Comment by lalithareddy007** [comment]
Check with your real email id, if you are getting notifications, you can merge the code

**Comment by Shemeeba** [comment]
Yes. I

 did check with my email Id and got the notification.

**Comment by Shemeeba** [comment]
Screenshot

**Comment by Shemeeba** [comment]
Screenshot 2023-12-22 160524

**Comment by Shemeeba** [comment]
Yes I did and got the notification on my email

**Pull request merged**
